// This files was initially generated by gemma-4-4eb, then edited by Marten Richter
// src/components/LazyYouTubeEmbed.js
import React, { useState } from 'react'

/**
 * A component that requires explicit user consent before rendering an externally hosted YouTube iframe
 * to comply with data privacy regulations (e.g., GDPR).
 * @param {string} videoId - The unique ID of the YouTube video.
 */
const LazyYouTubeEmbed = ({
  videoId,
  videoTitle
}: {
  videoId: string
  videoTitle: string
}) => {
  const [hasConsented, setHasConsented] = useState(false)

  const handleConsentClick = (event: React.ChangeEvent<HTMLInputElement>) => {
    setHasConsented(event.target.checked)
  }

  // Construct the full YouTube embed URL for loading
  const youtubeUrl = `https://www.youtube.com/embed/${videoId}?autoplay=1&rel=0`

  return (
    <div className='lazy-video-container p-4 my-6 border rounded bg-white shadow'>
      <div
        className='consent-disclosure-box mb-6 p-4 border-l-4'
        style={{ borderColor: 'var(--color-warning, orange)' }}
      >
        <h3>{videoTitle}</h3>
        {hasConsented && (
          <div className='video-wrapper'>
            <iframe
              className='w-full h-full'
              src={youtubeUrl}
              title={`Video Tutorial for Consent`}
              frameBorder='0'
              allowFullScreen
              allow='accelerometer; encrypted-media; gyroscope; picture-in-picture'
            ></iframe>
          </div>
        )}
        {!hasConsented && (
          <span
            aria-hidden='true'
            style={{
              alignItems: 'center',
              fontSize: '5rem',
              marginRight: '20rem',
              marginLeft: '20rem',
              justifyContent: 'center',
              width: '100%'
            }}
          >
            🎥
          </span>
        )}
        <div className='mt-4 flex items-start space-x-3'>
          <br />
          <input
            type='checkbox'
            checked={hasConsented}
            onChange={handleConsentClick}
            className='form-checkbox h-5 w-5 text-blue-600 bg-gray-100 border-gray-300 cursor-pointer'
          />
          <label
            htmlFor={`video-${videoId}`}
            className='text-base font-medium text-gray-800 cursor-pointer'
          >
            I consent to the viewing of this video, acknowledging that my
            activity (such as IP address and access date) will be transmitted to
            YouTube/Google. For more detailed information regarding data
            processing, please refer to the official Google Privacy Policy:{' '}
            <a
              href='https://policies.google.com/privacy'
              target='_blank'
              rel='noopener noreferrer'
              className='text-blue-600 hover:underline'
            >
              (Google Privacy Policies / Data Processing Agreement)
            </a>
            .
          </label>
        </div>
      </div>
    </div>
  )
}

export default LazyYouTubeEmbed
