name: Node.js Package deletion

on:
  push:
    branches:
      - 'master'
      - 'next'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Testing node.js package deletion workflow'

  
jobs:
  delete-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [
          'lectureapp',
          'app',
          'assets',
          'avkeystore',
          'config',
          'commonhandler',
          'data',
          'security',
          ]
    steps:
    - name: Delete old versions of ${{ matrix.package }}
      uses: actions/delete-package-versions@v4
      with: 
        package-name: ${{ matrix.package }}
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"
