name: Version Increment on security and maintenance release
on:
  workflow_dispatch:
   inputs:
      bump:
        description: 'Global version bump type'
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PUSH_TO_GIT }}
      - name: Git Config
        run: |
          git config --global user.name 'Fails maintenance bot'
          git config --global user.email 'marten.richter@freenet.de'
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Lerna Global Versioning
        run: |
          npx lerna version ${{ github.event.inputs.bump }} \
            --yes \
            --no-push \
            --message "chore(release): publish %s"
      - name: Push Changes
        run: |
          git push --tags
          git push
